### PR TITLE
Timeouts

### PR DESCRIPTION
**Pull request by zetok**
With this, it's possible to have a somewhat working DHT node.

I think that some things (`TimeoutQueue`, fields of `DhtNode` struct) should be named better, but I'm not sure how to name it.

---
This change is [Reviewable](https://reviewable.io/reviews/zetok/tox/91)

### CODE REVIEW

**Comment by kpp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht.rs, line 987 at r1](https://reviewable.io:443/reviews/zetok/tox/91#-KvcMOg-a_qRbO4fqvj_:-KvcMOg-a_qRbO4fqvja:baic9vn) ([raw file](https://github.com/zetok/tox/blob/6f570dc1fe2b8467206be661827a3f9686229dae/src/toxcore/dht.rs#L987)):*
> ```Rust
>     /// Check if node with given PK is in the `Bucket`.
>     pub fn contains(&self, pk: &PublicKey) -> bool {
>         self.nodes.iter().any(|n| n.pk() == pk)
> ```

Or you may use `::find` + check != None

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by zetok** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht.rs, line 987 at r1](https://reviewable.io:443/reviews/zetok/tox/91#-KvcMOg-a_qRbO4fqvj_:-KvlYrad4SoJLm3YuUWK:b-qvhkv4) ([raw file](https://github.com/zetok/tox/blob/6f570dc1fe2b8467206be661827a3f9686229dae/src/toxcore/dht.rs#L987)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Or you may use `::find` + check != None
</blockquote></details>

`self.find(pk).is_some()` is indeed slightly shorter, but `find()` keeps track of and allocates memory for its return value, which is more than what `self.iter().any(|n| n.pk() == pk)` allocates for its return value, so I feel slightly reluctant to use it.

Anyway, slightly refactored `find()` fns.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by kpp** [comment]
Reviewed 4 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/toxcore/dht.rs, line 987 at r1](https://reviewable.io:443/reviews/zetok/tox/91#-KvcMOg-a_qRbO4fqvj_:-Kw63a7MnKewzzxFZQ2m:byhs52a) ([raw file](https://github.com/zetok/tox/blob/6f570dc1fe2b8467206be661827a3f9686229dae/src/toxcore/dht.rs#L987)):*
> allocates memory for its return value
Don't thing about it.

---

*[src/toxcore/dht.rs, line 930 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63HJHqX-k4jJjbrIp:-Kw63HJImu3DxldaBWxE:bawouzt) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L930)):*
> ```Rust
>             Ok(index) => {
>                 debug!(target: "Bucket",
>                     "Updated: the node was already in the bucket.");
> ```

I added some keywords into this log message like `into the bucket` or `from the bucket`. You may remove them as long as you added `target: Bucket`

---

*[src/toxcore/dht.rs, line 1190 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63iPs7htOjevtdvDC:-Kw63iPs7htOjevtdvDD:b-ncx779) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L1190)):*
> ```Rust
>         debug!(target: "Kbucket", "Getting closest nodes.");
>         trace!(target: "Kbucket", "With PK: {:?} and self: {:?}", pk, self);
>         // TODO: optimize
> ```

It is optimized =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/toxcore/dht.rs, line 930 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63HJHqX-k4jJjbrIp:-Kw6FpFei-jYWLZSAjzb:b42k020) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L930)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

I added some keywords into this log message like `into the bucket` or `from the bucket`. You may remove them as long as you added `target: Bucket`
</blockquote></details>

`target` allows to selectively display log messages – if `debug` level is not enabled globally, only targets that are explicitly enabled with `debug` level are displayed. In case where multiple targets are displayed (or when `debug` is enabled globally) it's good for message to inform which part of the code exactly was triggered.

---

*[src/toxcore/dht.rs, line 1190 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63iPs7htOjevtdvDC:-Kw6HlQsjLWOyznTwRHi:b-il2e00) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L1190)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

It is optimized =)
</blockquote></details>

Is it though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by kpp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1190 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63iPs7htOjevtdvDC:-Kw6a2IlqK_wSBbmMzga:b-59n385) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L1190)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Is it though?
</blockquote></details>

yes. I checked that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by zetok** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1190 at r3](https://reviewable.io:443/reviews/zetok/tox/91#-Kw63iPs7htOjevtdvDC:-Kw7OpAxSkBzKz3eyFLF:bss4a2b) ([raw file](https://github.com/zetok/tox/blob/2cd798ac581db43ee38c5255422587e6285f40e7/src/toxcore/dht.rs#L1190)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

yes. I checked that
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91)*

**Comment by kpp** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/91#-:-KwAD17p4EdPq-TjNUgm:bnfp4nl)*

**Pull request merged**
