### PR TITLE
feat(dht_node): add fn for sending packets and method for handling them

### PR DESCRIPTION
**Pull request by zetok**
Depends on #81.

---
This change is [Reviewable](https://reviewable.io/reviews/zetok/tox/83)

### CODE REVIEW

**Comment by kpp** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht_node.rs, line 365 at r1](https://reviewable.io:443/reviews/zetok/tox/83#-Ku_2jzv9YOyPwBnKVlv:-Ku_2jzwTb7fZVHQpob9:b-wzsm03) ([raw file](https://github.com/zetok/tox/blob/ef8942cdf99d3bb3ce568f1ce26a93db7a492b98/src/toxcore/dht_node.rs#L365)):*
> ```Rust
> {
>     let (tx, rx) = mpsc::channel(2048);
>     drop(thread::spawn(move || {
> ```

don't use drop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83)*

**Comment by kpp** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht_node.rs, line 365 at r1](https://reviewable.io:443/reviews/zetok/tox/83#-Ku_2jzv9YOyPwBnKVlv:-Ku_b5UjQnpptcAoWLhP:bb038bp) ([raw file](https://github.com/zetok/tox/blob/ef8942cdf99d3bb3ce568f1ce26a93db7a492b98/src/toxcore/dht_node.rs#L365)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

don't use drop
</blockquote></details>

Dropping thread handle detaches the thread, which seems to be desirable here, since thread itself doesn't return anything..?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83)*

**Comment by kpp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht_node.rs, line 365 at r1](https://reviewable.io:443/reviews/zetok/tox/83#-Ku_2jzv9YOyPwBnKVlv:-Ku_cyN6PZkCeNuljNoN:b-fw86tc) ([raw file](https://github.com/zetok/tox/blob/ef8942cdf99d3bb3ce568f1ce26a93db7a492b98/src/toxcore/dht_node.rs#L365)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Dropping thread handle detaches the thread, which seems to be desirable here, since thread itself doesn't return anything..?
</blockquote></details>

It is detached unsless you call `join()`. See https://doc.rust-lang.org/std/thread/struct.JoinHandle.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht_node.rs, line 365 at r1](https://reviewable.io:443/reviews/zetok/tox/83#-Ku_2jzv9YOyPwBnKVlv:-Ku_gnV_n0-ORrNjRLr6:b-896fix) ([raw file](https://github.com/zetok/tox/blob/ef8942cdf99d3bb3ce568f1ce26a93db7a492b98/src/toxcore/dht_node.rs#L365)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

It is detached unsless you call `join()`. See https://doc.rust-lang.org/std/thread/struct.JoinHandle.html
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83)*

**Comment by kpp** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/83#-:-KudoInMKzXKHbAa53cJ:bnfp4nl)*

**Pull request merged**
