### PR TITLE
Improve tests for Bucket and Kbucket

### PR DESCRIPTION
**Pull request by kpp**
- [x] add methods `Bucket::find` and `Kbucket::find`
- [x] add tests `bucket_position_test` & `kbucket_position_test` to check whether nodes are added and removed (including their position in the buckets)

---
This change is [Reviewable](https://reviewable.io/reviews/zetok/tox/61)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1024 at r1](https://reviewable.io:443/reviews/zetok/tox/61#-Ktw_wPOi6cP2eB-Stgt:-Ktw_wPPl_JwM1S9lxWq:b7eextu) ([raw file](https://github.com/zetok/tox/blob/bfcc433e3d707f5d4137a899472cc8cbed0b7dcc/src/toxcore/dht.rs#L1024)):*
> ```Rust
>     /** Try to find [`PackedNode`](./struct.PackedNode.html) in the bucket
>     by PK. Used in tests to check whether a `PackedNode` was added or
>     removed.
> ```

Perhaps instead of adding public methods just for tests, the test should be moved to a submodule of the `dht` module like it's done in e.g. https://github.com/zetok/tox/blob/8358e2d4a607cebfb632cc66daf8a8d38aea026d/src/toxcore/dht_node.rs#L150,L151 ? Or does something other than tests need, or would need this functionality?

In a submodule tests would have access to private fields of a struct.

---

*[src/toxcore_tests/dht_tests.rs, line 1399 at r1](https://reviewable.io:443/reviews/zetok/tox/61#-Ktwc8H59egw0GFUOHKm:-Ktwc8H59egw0GFUOHKn:b-lf9i81) ([raw file](https://github.com/zetok/tox/blob/bfcc433e3d707f5d4137a899472cc8cbed0b7dcc/src/toxcore_tests/dht_tests.rs#L1399)):*
> ```Rust
>     fn with_nodes(nodes: Vec<PackedNode>) -> TestResult {
>         if nodes.len() > BUCKET_DEFAULT_SIZE {
>             // not all nodes will be inserted if
> ```

This is a bit confusing, since it states that nodes would always not be inserted if there are more than `BUCKET_DEFAULT_SIZE`, which is not the case, since it's just a possibility. Instead it should state that it's only probable, e.g.: `it's possible that not all nodes will be inserted if`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/61)*

**Comment by zetok** [comment]
Btw, if the `TODO` is not going to be a part of this PR, then it would be good to add it in the code, even if it's going to be done in the next PR after this one.

**Comment by kpp** [comment]
> Btw, if the `TODO` is not going to be a part of this PR, then it would be good to add it in the code, even if it's going to be done in the next PR after this one.

I am working on in.

**Comment by kpp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1024 at r1](https://reviewable.io:443/reviews/zetok/tox/61#-Ktw_wPOi6cP2eB-Stgt:-KtxKtSG7OIx_BEUeLjG:b-896fix) ([raw file](https://github.com/zetok/tox/blob/bfcc433e3d707f5d4137a899472cc8cbed0b7dcc/src/toxcore/dht.rs#L1024)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Perhaps instead of adding public methods just for tests, the test should be moved to a submodule of the `dht` module like it's done in e.g. https://github.com/zetok/tox/blob/8358e2d4a607cebfb632cc66daf8a8d38aea026d/src/toxcore/dht_node.rs#L150,L151 ? Or does something other than tests need, or would need this functionality?

In a submodule tests would have access to private fields of a struct.
</blockquote></details>

Done.

---

*[src/toxcore_tests/dht_tests.rs, line 1399 at r1](https://reviewable.io:443/reviews/zetok/tox/61#-Ktwc8H59egw0GFUOHKm:-KtxKqhQDeW_GP84hhgz:b-896fix) ([raw file](https://github.com/zetok/tox/blob/bfcc433e3d707f5d4137a899472cc8cbed0b7dcc/src/toxcore_tests/dht_tests.rs#L1399)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This is a bit confusing, since it states that nodes would always not be inserted if there are more than `BUCKET_DEFAULT_SIZE`, which is not the case, since it's just a possibility. Instead it should state that it's only probable, e.g.: `it's possible that not all nodes will be inserted if`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/61)*

**Comment by zetok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht.rs, line 1613 at r2](https://reviewable.io:443/reviews/zetok/tox/61#-Ku-66iZBeG0GYL-y95c:-Ku-66iZBeG0GYL-y95d:bl1h63b) ([raw file](https://github.com/zetok/tox/blob/f21992d99d155cb63652f2a0accc2e6a4bd53491/src/toxcore/dht.rs#L1613)):*
> ```Rust
>             let n2 = PackedNode::new(false, SocketAddr::V4(saddr), &pk2);
> 
>             pk_bytes[15-1] = 4;
> ```

Why not just write `14`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/61)*

**Comment by kpp** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/toxcore/dht.rs, line 1613 at r2](https://reviewable.io:443/reviews/zetok/tox/61#-Ku-66iZBeG0GYL-y95c:-Ku-FwHxz_3jw7wvF9SO:b-896fix) ([raw file](https://github.com/zetok/tox/blob/f21992d99d155cb63652f2a0accc2e6a4bd53491/src/toxcore/dht.rs#L1613)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Why not just write `14`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/61)*

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/61#-:-Ku-GQLzLejLSGR9qrUR:bnfp4nl)*

**Pull request merged**
