### PR TITLE
Switch algo of Bucket::try_add from O(N) to O(log N)

### PR DESCRIPTION
**Pull request by kpp**
* switch try_add/remove from linear search to binary search
* fix creating a PackedNode with `num = Some(0)`
* fix possible change of the nodes by user (it may cause the break of ordering)

---
This change is [Reviewable](https://reviewable.io/reviews/zetok/tox/59)

### CODE REVIEW

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/toxcore/dht.rs, line 1020 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXrWy38oBv5PxnrjLr:-KtXrWy38oBv5PxnrjLs:b-uiqbmh) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1020)):*
> ```Rust
>             self, pk, pn);
> 
>         if self.capacity == 0 {
> ```

Good catch. Check at the time of creation also should be added, and if it's created with `0` capacity there should be an `error!` message. I wonder if it actually could be made like port ranges in `network.rs` to never be `0`, and if that's not possible, then just returning `Option<Self>` is probably for the best. In addition to the documentation stating that creating bucket would fail if capacity = 0.

---

*[src/toxcore/dht.rs, line 1025 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXsW5qX9WBO9zVlajX:-KtXsW5qX9WBO9zVlajY:b-ln7kzp) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1025)):*
> ```Rust
>         }
> 
>         match self.nodes.binary_search_by( |node| pk.distance(&pn.pk, &node.pk)) {
> ```

Unnecessary space between `( |`

---

*[src/toxcore/dht.rs, line 1087 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXuqP_zc3FcxZrbh-M:-KtXuqP_zc3FcxZrbh-N:b-nj653v) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1087)):*
> ```Rust
>     /** Check if `Bucket` is full.
> 
>     Returns `true` if there are no free space in the `Bucket`, `false`
> ```

`there are` → `there is`

---

*[src/toxcore/dht.rs, line 1067 at r2](https://reviewable.io:443/reviews/zetok/tox/59#-KtXvsMY6c8xazZslxgP:-KtXvsMY6c8xazZslxgQ:bwvelgj) ([raw file](https://github.com/zetok/tox/blob/782017aac1bf0fbc0f802c7775434233b8873dfe/src/toxcore/dht.rs#L1067)):*
> ```Rust
>     pub fn remove(&mut self, pubkey: &PublicKey) {
>         trace!(target: "Bucket", "Removing PackedNode with PK: {:?}", pubkey);
>         match self.nodes.binary_search_by( |node| pubkey.cmp(&node.pk) ) {
> ```

Unnecessary spaces?

---

*[src/toxcore/dht.rs, line 1072 at r2](https://reviewable.io:443/reviews/zetok/tox/59#-KtXw1shgkriCzpZyB5Y:-KtXw1shgkriCzpZyB5Z:b-fxis46) ([raw file](https://github.com/zetok/tox/blob/782017aac1bf0fbc0f802c7775434233b8873dfe/src/toxcore/dht.rs#L1072)):*
> ```Rust
>             },
>             Err(_) => {
>                 trace!("Failed to remove PackedNode with PK: {:?}", pubkey);
> ```

Rather than failing to remove, there was no PackedNode with same PK – message should be updated to something like `No PackedNode to remove with PK: {}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59)*

**Comment by kpp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1020 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXrWy38oBv5PxnrjLr:-KtY9XoxhuvvpL-EKIn8:b-896fix) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1020)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Good catch. Check at the time of creation also should be added, and if it's created with `0` capacity there should be an `error!` message. I wonder if it actually could be made like port ranges in `network.rs` to never be `0`, and if that's not possible, then just returning `Option<Self>` is probably for the best. In addition to the documentation stating that creating bucket would fail if capacity = 0.
</blockquote></details>

Done.

---

*[src/toxcore/dht.rs, line 1025 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXsW5qX9WBO9zVlajX:-KtY9_J04Zn_nw5Dsh4x:b-896fix) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1025)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Unnecessary space between `( |`
</blockquote></details>

Done.

---

*[src/toxcore/dht.rs, line 1087 at r1](https://reviewable.io:443/reviews/zetok/tox/59#-KtXuqP_zc3FcxZrbh-M:-KtY9ekG-Ei-XKIor36r:b-896fix) ([raw file](https://github.com/zetok/tox/blob/c6a282d55b6b824c36986db6bee844d29301cd99/src/toxcore/dht.rs#L1087)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`there are` → `there is`
</blockquote></details>

Done.

---

*[src/toxcore/dht.rs, line 1067 at r2](https://reviewable.io:443/reviews/zetok/tox/59#-KtXvsMY6c8xazZslxgP:-KtY9c40ogUuH9wMf4jC:b-896fix) ([raw file](https://github.com/zetok/tox/blob/782017aac1bf0fbc0f802c7775434233b8873dfe/src/toxcore/dht.rs#L1067)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Unnecessary spaces?
</blockquote></details>

Done.

---

*[src/toxcore/dht.rs, line 1072 at r2](https://reviewable.io:443/reviews/zetok/tox/59#-KtXw1shgkriCzpZyB5Y:-KtY9bJvECSp0sbh8plx:b-896fix) ([raw file](https://github.com/zetok/tox/blob/782017aac1bf0fbc0f802c7775434233b8873dfe/src/toxcore/dht.rs#L1072)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Rather than failing to remove, there was no PackedNode with same PK – message should be updated to something like `No PackedNode to remove with PK: {}`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59)*

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore_tests/dht_tests.rs, line 1248 at r5](https://reviewable.io:443/reviews/zetok/tox/59#-KtYQUW_A_YkybYy67jX:-KtYQUW_A_YkybYy67jY:bndehvc) ([raw file](https://github.com/zetok/tox/blob/2871532412fe35171989c780649c7d6a8ae19929/src/toxcore_tests/dht_tests.rs#L1248)):*
> ```Rust
>     fn with_capacity(num: u8) -> TestResult {
>         if num != 0 {
>             return TestResult::discard()
> ```

Running it via quickcheck is not needed since the test accepts only a single value – it would be better to just hardcode the value without using quickcheck.

---

*[src/toxcore_tests/dht_tests.rs, line 1289 at r5](https://reviewable.io:443/reviews/zetok/tox/59#-KtYR1r0NUznf_4bd6xN:-KtYR1r0NUznf_4bd6xO:b6u4x9s) ([raw file](https://github.com/zetok/tox/blob/2871532412fe35171989c780649c7d6a8ae19929/src/toxcore_tests/dht_tests.rs#L1289)):*
> ```Rust
> fn bucket_new_some_default_test() {
>     fn with_capacity(num: u8) -> TestResult {
>         if num as usize != BUCKET_DEFAULT_SIZE {
> ```

Same as the test above with `0` – it would be better to hardcode the single value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59)*

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1058 at r6](https://reviewable.io:443/reviews/zetok/tox/59#-KtugP2Ey19Sb3v6__V6:-KtugP2F9tG8qoWvC2AO:b-hwbz73) ([raw file](https://github.com/zetok/tox/blob/e10f3b71f2d25cc81cd372355b2dc0281c03ca5b/src/toxcore/dht.rs#L1058)):*
> ```Rust
>             Err(index) => {
>                 if index == self.nodes.len() {
>                     // index is pointing past to the end
> ```

`s/to //` ?

---

*[src/toxcore/dht.rs, line 1116 at r7](https://reviewable.io:443/reviews/zetok/tox/59#-Ku-irp1hUEh4oaGPhsX:-Ku-irp21Ovi-Cf6jCxt:b-h81aqh) ([raw file](https://github.com/zetok/tox/blob/f63814241469573c556fae2eded8c6f13a64bb94/src/toxcore/dht.rs#L1116)):*
> ```Rust
>     pub fn remove(&mut self, base_pk: &PublicKey, node_pk: &PublicKey) {
>         trace!(target: "Bucket", "Removing PackedNode with PK: {:?}", node_pk);
>         match self.nodes.binary_search_by(|node| base_pk.distance(node.pk(), node_pk) ) {
> ```

I think that `node` needs to be renamed to something different (e.g. `n`), since there's very little of visual disparity between `node.pk()` and `node_pk`, which makes things a bit confusing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59)*

**Comment by kpp** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/toxcore/dht.rs, line 1116 at r7](https://reviewable.io:443/reviews/zetok/tox/59#-Ku-irp1hUEh4oaGPhsX:-Ku03-YmuNdhe3LykqD6:b-896fix) ([raw file](https://github.com/zetok/tox/blob/f63814241469573c556fae2eded8c6f13a64bb94/src/toxcore/dht.rs#L1116)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

I think that `node` needs to be renamed to something different (e.g. `n`), since there's very little of visual disparity between `node.pk()` and `node_pk`, which makes things a bit confusing. 
</blockquote></details>

Done.

---

*[src/toxcore_tests/dht_tests.rs, line 1248 at r5](https://reviewable.io:443/reviews/zetok/tox/59#-KtYQUW_A_YkybYy67jX:-Ku0362bT17IUDP-aWLM:b-896fix) ([raw file](https://github.com/zetok/tox/blob/2871532412fe35171989c780649c7d6a8ae19929/src/toxcore_tests/dht_tests.rs#L1248)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Running it via quickcheck is not needed since the test accepts only a single value – it would be better to just hardcode the value without using quickcheck.
</blockquote></details>

Done.

---

*[src/toxcore_tests/dht_tests.rs, line 1289 at r5](https://reviewable.io:443/reviews/zetok/tox/59#-KtYR1r0NUznf_4bd6xN:-Ku036ZYuSc9GDR95Boi:b-896fix) ([raw file](https://github.com/zetok/tox/blob/2871532412fe35171989c780649c7d6a8ae19929/src/toxcore_tests/dht_tests.rs#L1289)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Same as the test above with `0` – it would be better to hardcode the single value
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59)*

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/59#-:-Ku-t4oD95rJqT8kWAJS:bnfp4nl)*

**Pull request merged**
